---

- name: Installation packages
  become: true 
  with_items: "{{ ubuntu_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: Setup ufw
  become: true
  with_items: "{{ ufw_rules }}"
  ufw:
    name: "{{ item.rules }}"
    role: allow
